server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms-route # \u5546\u54C1\u7BA1\u7406\u8DEF\u7531
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms-route # \u8BA2\u5355\u7BA1\u7406\u8DEF\u7531
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route # \u7528\u6237\u7BA1\u7406\u8DEF\u7531
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route # \u4ED3\u5E93\u7BA1\u7406\u8DEF\u7531
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: sms-route # \u8425\u9500\u7BA1\u7406\u8DEF\u7531
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        - id: index-route1
          uri: lb://index-service
          predicates:
            - Host=www.gmall.com,gmall.com
          filters:
            - Auth=/xxx, /yyy
        - id: index-route2
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Host=auth.gmall.com,sso.gmall.com
          filters:
            - AddResponseHeader=xxxxxx, yyyyyy, zzzzzz
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
        - id: order-route
          uri: lb://order-service
          predicates:
            - Host=order.gmall.com
          filters:
            - Auth=/
        - id: payment-route
          uri: lb://payment-service
          predicates:
            - Host=payment.gmall.com
          filters:
            - Auth=/
        - id: payment-route1
          uri: lb://payment-service
          predicates:
            - Path=/pay/**

jwt:
  pubKeyPath: D:\project\rsa\rsa.pub
  cookieName: GMALL_TOKEN